name: My first Jekyll site
markdown: kramdown # redcarpet
# highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json", "README.md", "*.txt"]
include: ["_posts"]
